name: react build & deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Dependencies Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: ""

      - name: Generate .nojekyll
        run: touch build/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
          git-config-name: Build-Deploy Bot
          git-config-email: <>
