name: npm build & publish
on:
  release:
    types: [created]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org/"

      - name: Configure package.json
        run: |
          npx json -f '.\package copy.json' -I -e "delete this.devDependencies"
          npx json -f '.\package copy.json' -I -e "delete this.dependencies['react-syntax-highlighter']"

      - name: Dependencies Install
        run: npm install

      - name: Build
        run: npm run npm:build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
